# Generated by Django 3.2.9 on 2022-07-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_mailmessage_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=124)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=2000)),
                ('comment', models.TextField()),
            ],
        ),
    ]
