# Generated by Django 3.2.9 on 2022-07-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0005_delete_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
