# Generated by Django 3.2.9 on 2022-07-29 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0006_delete_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailMessage',
        ),
    ]
